name: Development CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  test-and-build:
    name: Test & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.0"
          channel: "stable"

      - name: Get dependencies
        run: flutter pub get

      - name: Run tests with coverage
        run: flutter test --coverage --reporter=expanded

      - name: Analyze code
        run: flutter analyze --no-fatal-infos

      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Build APK (Debug)
        run: flutter build apk --debug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
          retention-days: 7

      - name: Upload coverage reports to Codecov
        if: success()
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: yhafiane7/gmsoft-municipal-infractions-mobile
          fail_ci_if_error: false
